In [28]:
import pandas as pd 

df = pd.read_csv("06_titanic_data_dirty (1).csv")

In [32]:
df.info()

<class 'pandas.DataFrame'>
Index: 600 entries, 0 to 615
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  600 non-null    int64
 1   Survived     597 non-null    str
 2   Pclass       594 non-null    str
 3   Name         600 non-null    str
 4   Sex          595 non-null    str
 5   Age          484 non-null    str
 6   SibSp        600 non-null    int64
 7   Parch        600 non-null    int64
 8   Ticket       600 non-null    str
 9   Fare         588 non-null    str
 10  Cabin        133 non-null    str
 11  Embarked     592 non-null    str
dtypes: int64(3), str(9)
memory usage: 89.9 KB

In [35]:
print("Dataset shape:", df.shape)

Dataset shape: (600, 12)

In [36]:
print(df.columns.tolist())

['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

In [37]:
df.info()

<class 'pandas.DataFrame'>
Index: 600 entries, 0 to 615
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  600 non-null    int64
 1   Survived     597 non-null    str
 2   Pclass       594 non-null    str
 3   Name         600 non-null    str
 4   Sex          595 non-null    str
 5   Age          484 non-null    str
 6   SibSp        600 non-null    int64
 7   Parch        600 non-null    int64
 8   Ticket       600 non-null    str
 9   Fare         588 non-null    str
 10  Cabin        133 non-null    str
 11  Embarked     592 non-null    str
dtypes: int64(3), str(9)
memory usage: 89.9 KB

In [38]:
print(df.isnull().sum())

PassengerId      0
Survived         3
Pclass           6
Name             0
Sex              5
Age            116
SibSp            0
Parch            0
Ticket           0
Fare            12
Cabin          467
Embarked         8
dtype: int64

In [29]:
df.duplicated().sum()

np.int64(10)

In [30]:
df = df.drop_duplicates(subset="PassengerId", keep="first")

In [39]:
df.dtypes

PassengerId    int64
Survived         str
Pclass           str
Name             str
Sex              str
Age              str
SibSp          int64
Parch          int64
Ticket           str
Fare             str
Cabin            str
Embarked         str
dtype: object

In [41]:
display(df.head().T)

,0,1,2,3,4
PassengerId,1,2,4,5,6
Survived,0,1,1,0,0
Pclass,3,1,1,3,3
Name,"Braund, Mr. Owen Harris","Cumings, Mrs. John Bradley (Florence Briggs Th...","Futrelle, Mrs. Jacques Heath (Lily May Peel)","Allen, Mr. William Henry","Moran, Mr. James"
Sex,male,female,female,male,male
Age,22,38,35,35,NaN
SibSp,1,1,1,0,0
Parch,0,0,0,0,0
Ticket,A/5 21171,PC 17599,113803,373450,330877
Fare,7.25,71.2833,53.1,8.05,8.4583
Cabin,NaN,C85,C123,NaN,NaN
Embarked,S,C,S,S,Q

In [42]:
print(df.isnull().sum())

PassengerId      0
Survived         3
Pclass           6
Name             0
Sex              5
Age            116
SibSp            0
Parch            0
Ticket           0
Fare            12
Cabin          467
Embarked         8
dtype: int64

In [53]:
df["Age"] = df["Age"].astype(str).str.replace("yrs", "", regex=False).str.strip()

In [54]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")

In [55]:

df["Age"] = df["Age"].fillna(df["Age"].median())

In [56]:
df["Age"].isnull().sum()

np.int64(0)

In [48]:
for col in ["Name", "Sex", "Embarked"]:
    df[col] = df[col].str.strip()

In [49]:

print(df["Age"].describe())

count    600.000000
mean      32.635417
std       42.566701
min       -4.000000
25%       23.000000
50%       29.000000
75%       36.000000
max      999.000000
Name: Age, dtype: float64

In [50]:

print(df[df["Age"] > 100])

     PassengerId Survived Pclass                          Name     Sex    Age  \
420          608        1      1   Daniel, Mr. Robert Williams    male  200.0
493          717        1      1  Endres, Miss Caroline Louise  female  150.0
500          724        0      2       Hodges, Mr. Henry Price    male  999.0

     SibSp  Parch    Ticket     Fare Cabin     Embarked
420      0      0    113804     30.5   NaN  Southampton
493      0      0  PC 17757  227.525   C45            C
500      0      0    250643       13   NaN            S

In [52]:
import numpy as np 
df.loc[df["Age"] > 100, "Age"] = np.nan
df.loc[df["Age"] < 0, "Age"] = np.nan

df["Age"] = df["Age"].fillna(df["Age"].median())

In [57]:
df["Fare"] = df["Fare"].astype(str).str.replace("£", "", regex=False).str.strip()

In [58]:
df["Fare"] = pd.to_numeric(df["Fare"], errors="coerce")
df.loc[(df["Fare"] < 0) | (df["Fare"] > 600), "Fare"] = np.nan

In [60]:
df.describe()

       PassengerId         Age       SibSp       Parch        Fare
count   600.000000  600.000000  600.000000  600.000000  582.000000
mean    444.333333   30.587083    0.566667    0.390000   32.887874
std     255.408721   13.295784    1.470542    0.948366   53.800641
min       1.000000    0.420000   -2.000000   -1.000000    0.000000
25%     225.750000   23.375000    0.000000    0.000000    7.895800
50%     444.500000   29.000000    0.000000    0.000000   14.454200
75%     667.250000   36.000000    1.000000    0.000000   30.646850
max     891.000000   95.000000   20.000000   12.000000  512.329000

In [61]:
df.loc[df["SibSp"] < 0, "SibSp"] = np.nan
df.loc[df["Parch"] < 0, "Parch"] = np.nan

In [62]:
df["Fare"] = df["Fare"].fillna(df["Fare"].median())

In [69]:
df["Cabin"] = df["Cabin"].fillna(df["Cabin"].mode()[0])

In [71]:
df.isnull().sum()

PassengerId    0
Survived       3
Pclass         6
Name           0
Sex            5
Age            0
SibSp          2
Parch          1
Ticket         0
Fare           0
Cabin          0
Embarked       8
dtype: int64

In [74]:
df.Embarked.unique()

<ArrowStringArray>
['S', 'C', 'Q', 's', nan, 'Southampton', 'X', 'c', 'Queenstown', 'Cherbourg']
Length: 10, dtype: str

In [75]:
df["Embarked"]= df["Cabin"].fillna(df["Cabin"].mode()[0])